#!/usr/bin/env bash
(cat <<EOF
d lib 0755 root sys
d lib/svc 0755 root sys
d lib/svc/manifest 0755 root sys
d lib/svc/manifest/system 0644 root sys
f lib/svc/manifest/system/wiggle.xml 0644 root sys
d var/db 0755 root sys
d var/db/wiggle 0755 root sys
d var/db/wiggle/db 0755 root sys
d var/log 0755 root sys
d var/log/wiggle 0755 root sys
d fifo 0755 root sys
EOF
for i in `find rel/wiggle | grep -v '.DS_Store'`
do
  file=`echo $i| sed -e 's;^rel/;fifo/;'`
  PERM=`ls -l $i  | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf("0%0o\n",k)}' | head -n 1`
  if [ "x$PERM" == "x" ]
  then
    PERM=`ls -l $i  | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf("0%0o\n",k)}' | head -n 1`
  fi
  if [ "x$PERM" == "x" ]
  then
    PERM=0755
  fi

  OWNER=root
  GROUP=sys
  if echo $i | grep '/bin/'>/dev/null || echo $i | grep '/bin$'>/dev/null
  then
    GROUP=bin
  fi
  if [ -d $i ]
  then
  	echo d $file $PERM $OWNER $GROUP
  else
  	echo f $file $PERM $OWNER $GROUP
  fi
done) | sort
